name: Build DS920+ 7.0.1-42218

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS920+
            version: 7.0.1-42218

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
        
      - name: 获取当前时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: 获取项目描述
        id: desc
        run: |
          wget https://raw.githubusercontent.com/Online24Hours/Redpill_Build/main/README.MD -O /home/runner/desc.txt
          echo "::set-output name=description::$(cat /home/runner/desc.txt)"
        
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/jumkey/redpill-load.git /home/runner/redpill-load
          wget https://raw.githubusercontent.com/Online24Hours/Redpill_Build/main/ds920p_user_config.json -O /home/runner/redpill-load/ds920p_user_config.json
          wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill/releases/redpill-4.4.180plus-geminilake.tgz
          tar zxvf redpill-4.4.180plus-geminilake.tgz -C ./
          mv ./redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
          
      - name: 添加扩展驱动
        run: |
          cd /home/runner/redpill-load 
          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-dtb-static/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmw_pvscsi/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/igc/rpext-index.json'
          
      - name: 编译引导
        run: |
          cd /home/runner/redpill-load
          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
          
      - name: 上传引导镜像到 Github Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Redpill-load
          name: ${{matrix.version}} Build ${{steps.date.outputs.today}}
          body: ${{steps.desc.outputs.description}}
          draft: false
          prerelease: false
          files: |
            /home/runner/redpill-load/images/*.img
            
      - name: 删除旧的 Release 项目
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: Online24Hours/Redpill_Build
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: 上传引导镜像到 Github Actions
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{matrix.platform}} ${{matrix.version}}
#          path: /home/runner/redpill-load/images/*.img
#          if-no-files-found: error
